// Code generated by "stringer -type=BusinessErrorCode"; DO NOT EDIT.

package response

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownBusinessError-10000]
	_ = x[UserNotFoundError-10001]
	_ = x[InvalidUsernameOrPasswordError-10002]
	_ = x[InvalidOldPasswordError-10003]
	_ = x[UserExistsError-10004]
	_ = x[InvalidTokenError-10005]
	_ = x[AssetNotFoundError-11001]
	_ = x[DeviceNotFoundError-12001]
	_ = x[DeviceMacExistsError-12002]
	_ = x[UnknownDeviceTypeError-12003]
	_ = x[DeviceCommandSendFailedError-12004]
	_ = x[DeviceCommandSendTimeoutError-12005]
	_ = x[DeviceCommandExecFailedError-12006]
	_ = x[UnknownDeviceCommandTypeError-12007]
	_ = x[FirmwareNotFoundError-13001]
	_ = x[FirmwareFormatError-13002]
	_ = x[FirmwareExistsError-13003]
	_ = x[NetworkNotFoundError-14001]
}

const (
	_BusinessErrorCode_name_0 = "UnknownBusinessErrorUserNotFoundErrorInvalidUsernameOrPasswordErrorInvalidOldPasswordErrorUserExistsErrorInvalidTokenError"
	_BusinessErrorCode_name_1 = "AssetNotFoundError"
	_BusinessErrorCode_name_2 = "DeviceNotFoundErrorDeviceMacExistsErrorUnknownDeviceTypeErrorDeviceCommandSendFailedErrorDeviceCommandSendTimeoutErrorDeviceCommandExecFailedErrorUnknownDeviceCommandTypeError"
	_BusinessErrorCode_name_3 = "FirmwareNotFoundErrorFirmwareFormatErrorFirmwareExistsError"
	_BusinessErrorCode_name_4 = "NetworkNotFoundError"
)

var (
	_BusinessErrorCode_index_0 = [...]uint8{0, 20, 37, 67, 90, 105, 122}
	_BusinessErrorCode_index_2 = [...]uint8{0, 19, 39, 61, 89, 118, 146, 175}
	_BusinessErrorCode_index_3 = [...]uint8{0, 21, 40, 59}
)

func (i BusinessErrorCode) String() string {
	switch {
	case 10000 <= i && i <= 10005:
		i -= 10000
		return _BusinessErrorCode_name_0[_BusinessErrorCode_index_0[i]:_BusinessErrorCode_index_0[i+1]]
	case i == 11001:
		return _BusinessErrorCode_name_1
	case 12001 <= i && i <= 12007:
		i -= 12001
		return _BusinessErrorCode_name_2[_BusinessErrorCode_index_2[i]:_BusinessErrorCode_index_2[i+1]]
	case 13001 <= i && i <= 13003:
		i -= 13001
		return _BusinessErrorCode_name_3[_BusinessErrorCode_index_3[i]:_BusinessErrorCode_index_3[i+1]]
	case i == 14001:
		return _BusinessErrorCode_name_4
	default:
		return "BusinessErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
