package devicetype

type VibrationTemperature3Axis struct{}

func (VibrationTemperature3Axis) ID() uint {
	return VibrationTemperature3AxisType
}

func (VibrationTemperature3Axis) SensorID() uint {
	return VibrationRmsFFTXYZTemperatureSensor
}

func (VibrationTemperature3Axis) Settings() Settings {
	return []Setting{
		{
			Name:     "采集周期",
			Key:      "schedule0_sample_period",
			Type:     Uint32ValueType,
			Value:    1200000, // 20 minutes
			Category: SensorsSettingCategory,
			Options:  samplePeriodOption1,
			Sort:     0,
		},
		{
			Name:  "是否启用原始数据采集",
			Key:   "schedule1_sensor_flags",
			Type:  Uint64ValueType,
			Value: 32,
			Options: map[int]string{
				0:  "不启用",
				32: "启用",
			},
			Category: SensorsSettingCategory,
			Sort:     1,
		},
		{
			Name:     "原始数据采集周期",
			Key:      "schedule1_sample_period",
			Type:     Uint32ValueType,
			Value:    1200000, // 20 minutes
			Category: SensorsSettingCategory,
			Options:  samplePeriodOption1,
			Unit:     "ms",
			Sort:     2,
			Parent:   "schedule1_sensor_flags",
			Show:     32,
		},
		{
			Name:     "原始数据采集延时",
			Key:      "schedule1_sample_time_offset",
			Type:     Uint32ValueType,
			Value:    0,
			Category: SensorsSettingCategory,
			Sort:     3,
			Options:  smaplePeriodOffsetOption1,
			Parent:   "schedule1_sensor_flags",
			Show:     32,
		},
		{
			Name:     "原始数据采集量程",
			Key:      "kx122_continuous_range",
			Type:     Uint8ValueType,
			Value:    2,
			Category: SensorsSettingCategory,
			Options: map[int]string{
				0: "2g",
				1: "4g",
				2: "8g",
			},
			Unit:   "g",
			Sort:   4,
			Parent: "schedule1_sensor_flags",
			Show:   32,
		},
		{
			Name:     "原始数据采集频率",
			Key:      "kx122_continuous_odr",
			Type:     Uint8ValueType,
			Value:    12,
			Category: SensorsSettingCategory,
			Options: map[int]string{
				12: "3.2kHz",
				13: "6.4kHz",
				14: "12.8kHz",
				15: "25.6kHz",
			},
			Unit:   "Hz",
			Sort:   5,
			Parent: "schedule1_sensor_flags",
			Show:   32,
		},
	}
}

func (VibrationTemperature3Axis) Properties(sensorID uint) Properties {
	switch sensorID {
	case VibrationRmsFFTXYZTemperatureSensor:
		return Properties{
			{
				Key:         "vibration_severity",
				Name:        "振动烈度",
				Unit:        "mm/s",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        0,
				DataIndexes: []uint{1, 17, 33},
			},
			{
				Key:         "enveloping_pk2pk",
				Name:        "加速度包络",
				Unit:        "gE",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        1,
				DataIndexes: []uint{3, 19, 35},
			},
			{
				Key:         "acceleration_peak",
				Name:        "加速度峰值",
				Unit:        "m/s²",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        2,
				DataIndexes: []uint{5, 21, 37},
			},
			{
				Key:         "temperature",
				Name:        "温度",
				Unit:        "°C",
				Type:        FloatPropertyType,
				Precision:   3,
				Sort:        3,
				DataIndexes: []uint{73},
			},
			{
				Key:         "fft_frequency",
				Name:        "频率",
				Unit:        "Hz",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        4,
				DataIndexes: []uint{52, 60, 68},
			},
			{
				Key:         "displacement_peak_difference",
				Name:        "位移峰峰值",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        5,
				DataIndexes: []uint{6, 22, 38},
			},
			{
				Key:         "acceleration_rms",
				Name:        "加速度有效值",
				Unit:        "m/s²",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        6,
				DataIndexes: []uint{0, 16, 32},
			},
			{
				Key:         "crest_factor",
				Name:        "波峰因子",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        7,
				DataIndexes: []uint{5, 21, 37},
			},
			{
				Key:         "pulse_factor",
				Name:        "脉冲因子",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        8,
				DataIndexes: []uint{12, 28, 44},
			},
			{
				Key:         "margin_factor",
				Name:        "裕度因子",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        9,
				DataIndexes: []uint{11, 27, 43},
			},
			{
				Key:         "kurtosis",
				Name:        "峭度",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        10,
				DataIndexes: []uint{7, 23, 39},
			},
			{
				Key:         "kurtosis_norm",
				Name:        "峭度指标",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        11,
				DataIndexes: []uint{8, 24, 40},
			},
			{
				Key:         "skewness",
				Name:        "歪度",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        12,
				DataIndexes: []uint{9, 25, 41},
			},
			{
				Key:         "skewness_norm",
				Name:        "歪度指标",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        13,
				DataIndexes: []uint{10, 26, 42},
			},
			{
				Key:         "fft_value_1",
				Name:        "一倍频",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        14,
				DataIndexes: []uint{51, 59, 67},
			},
			{
				Key:         "fft_value_2",
				Name:        "二倍频",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        14,
				DataIndexes: []uint{53, 61, 69},
			},
			{
				Key:         "fft_value_3",
				Name:        "三倍频",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        15,
				DataIndexes: []uint{55, 63, 71},
			},
			{
				Key:         "fft_value_0",
				Name:        "半倍频",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        16,
				DataIndexes: []uint{49, 57, 65},
			},
			{
				Key:         "spectrum_variance",
				Name:        "谱方差",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        17,
				DataIndexes: []uint{13, 29, 45},
			},
			{
				Key:         "spectrum_mean",
				Name:        "谱均值",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        18,
				DataIndexes: []uint{14, 30, 46},
			},
			{
				Key:         "spectrum_rms",
				Name:        "谱有效值",
				Unit:        "",
				Type:        AxisPropertyType,
				Precision:   3,
				Sort:        19,
				DataIndexes: []uint{15, 31, 47},
			},
			{
				Key:         "inclination",
				Name:        "倾角",
				Unit:        "",
				Type:        FloatPropertyType,
				Precision:   3,
				Sort:        20,
				DataIndexes: []uint{48},
			},
		}
	}
	return nil
}
