export enum MonitoringPointTypeValue {
  LOOSENING_ANGLE = 10101,
  THICKNESS = 10201,
  THICKNESS_HIGH = 10202,
  PRELOAD = 10301,
  VIBRATION = 10401,
  PRESSURE = 10601,
  PRESSURE_TEMPERATURE = 10602,
  FLANGE_PRELOAD = 10311,
  TEMPERATURE = 10801,
  TOWER_INCLINATION = 10511,
  TOWER_BASE_SETTLEMENT = 10512,
  PRELOAD_ATTITUDE = 10303,
  VIBRATION_RPM = 10402,
  VIBRATION_THREE_AXIS_RPM = 10403
}

export enum MonitoringPointTypeText {
  LOOSENING_ANGLE = 'FIELD_LOOSENING_ANGLE',
  THICKNESS = 'FIELD_THICKNESS',
  THICKNESS_HIGH = 'FIELD_THICKNESS_HIGH',
  PRELOAD = 'SETTING_GROUP_PRELOAD',
  VIBRATION = 'VIBRATION',
  PRESSURE = 'FIELD_PRESSURE2',
  PRESSURE_TEMPERATURE = 'DEVICE_TYPE_PRESSURE_TEMPERATURE',
  FLANGE_PRELOAD = 'FLANGE_PRELOAD',
  TEMPERATURE = 'FIELD_TEMPERATURE',
  TOWER_INCLINATION = 'TOWER_INCLINATION',
  TOWER_BASE_SETTLEMENT = 'TOWER_BASE_SETTLEMENT',
  PRELOAD_ATTITUDE = 'PRELOAD_ATTITUDE',
  VIBRATION_RPM = 'VIBRATION_RPM',
  VIBRATION_THREE_AXIS_RPM = 'VIBRATION_THREE_AXIS_RPM'
}
