import { MonitoringPointTypeValue } from '../../../config';
import { PROPERTY_CATEGORIES } from '../../../constants/properties';

export const MONITORING_POINT_DISPLAY_PROPERTIES = {
  [MonitoringPointTypeValue.LOOSENING_ANGLE]: PROPERTY_CATEGORIES.SA,
  [MonitoringPointTypeValue.PRELOAD]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.FLANGE_PRELOAD]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.PRELOAD_ATTITUDE]: PROPERTY_CATEGORIES.SAS,
  [MonitoringPointTypeValue.THICKNESS]: PROPERTY_CATEGORIES.DC_NORMAL,
  [MonitoringPointTypeValue.THICKNESS_HIGH]: PROPERTY_CATEGORIES.DC_NORMAL,
  [MonitoringPointTypeValue.VIBRATION]: PROPERTY_CATEGORIES.SVT210R,
  [MonitoringPointTypeValue.VIBRATION_RPM]: PROPERTY_CATEGORIES.SVT220S1S3,
  [MonitoringPointTypeValue.VIBRATION_THREE_AXIS_RPM]: PROPERTY_CATEGORIES.SVT220S1S3,
  [MonitoringPointTypeValue.TOWER_INCLINATION]: PROPERTY_CATEGORIES.TOWER_INCLINATION,
  [MonitoringPointTypeValue.TOWER_BASE_SETTLEMENT]: PROPERTY_CATEGORIES.TOWER_BASE_SETTLEMENT,
  [MonitoringPointTypeValue.TEMPERATURE]: PROPERTY_CATEGORIES.ST,
  [MonitoringPointTypeValue.PRESSURE_TEMPERATURE]: PROPERTY_CATEGORIES.SPT
};

export const MONITORING_POINT = 'MONITORING_POINT';
export const MONITORING_POINT_LIST = `MONITORING_POINT_LIST`;
export const INVALID_MONITORING_POINT = `ABNORMAL_MONITORING_POINT`;
