package measurementtype

type Vibration3Axis struct {
}

func (Vibration3Axis) ID() uint {
	return Vibration3AxisType
}

func (Vibration3Axis) Variables() Variables {
	return []Variable{
		{
			Name:      "vibration_severity",
			Title:     "振动烈度",
			DataIndex: 1,
			Unit:      "mm/s",
			Type:      AxisVariableType,
			Precision: 3,
			Primary:   true,
			Sort:      0,
		},
		{
			Name:      "enveloping_pk2pk",
			Title:     "加速度包络",
			DataIndex: 3,
			Unit:      "gE",
			Type:      AxisVariableType,
			Precision: 3,
			Primary:   true,
			Sort:      1,
		},
		{
			Name:      "acceleration_peak",
			Title:     "加速度峰值",
			DataIndex: 5,
			Unit:      "m/s²",
			Type:      AxisVariableType,
			Precision: 3,
			Primary:   true,
			Sort:      2,
		},
		{
			Name:      "temperature",
			Title:     "温度",
			DataIndex: 73,
			Unit:      "°C",
			Type:      FloatVariableType,
			Precision: 3,
			Primary:   true,
			Sort:      3,
		},
		{
			Name:      "fft_frequency",
			Title:     "频率",
			DataIndex: 52,
			Unit:      "Hz",
			Type:      AxisVariableType,
			Precision: 3,
			Primary:   true,
			Sort:      4,
		},
		{
			Name:      "displacement_peak_difference",
			Title:     "位移峰峰值",
			DataIndex: 7,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      5,
		},
		{
			Name:      "acceleration_rms",
			Title:     "加速度有效值",
			DataIndex: 0,
			Unit:      "m/s²",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      6,
		},
		{
			Name:      "crest_factor",
			Title:     "波峰因子",
			DataIndex: 5,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      7,
		},
		{
			Name:      "pulse_factor",
			Title:     "脉冲因子",
			DataIndex: 12,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      8,
		},
		{
			Name:      "margin_factor",
			Title:     "裕度因子",
			DataIndex: 11,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      9,
		},
		{
			Name:      "kurtosis",
			Title:     "峭度",
			DataIndex: 7,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      10,
		},
		{
			Name:      "kurtosis_norm",
			Title:     "峭度指标",
			DataIndex: 8,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      11,
		},
		{
			Name:      "skewness",
			Title:     "歪度",
			DataIndex: 9,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      12,
		},
		{
			Name:      "skewness_norm",
			Title:     "歪度指标",
			DataIndex: 10,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      13,
		},
		{
			Name:      "fft_value_1",
			Title:     "一倍频",
			DataIndex: 51,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      14,
		},
		{
			Name:      "fft_value_2",
			Title:     "二倍频",
			DataIndex: 53,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      14,
		},
		{
			Name:      "fft_value_3",
			Title:     "三倍频",
			DataIndex: 55,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      15,
		},
		{
			Name:      "fft_value_0",
			Title:     "半倍频",
			DataIndex: 49,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      16,
		},
		{
			Name:      "spectrum_variance",
			Title:     "谱方差",
			DataIndex: 13,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      17,
		},
		{
			Name:      "spectrum_mean",
			Title:     "谱均值",
			DataIndex: 14,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      18,
		},
		{
			Name:      "spectrum_rms",
			Title:     "谱有效值",
			DataIndex: 15,
			Unit:      "",
			Type:      AxisVariableType,
			Precision: 3,
			Sort:      19,
		},
		{
			Name:      "inclination",
			Title:     "倾角",
			DataIndex: 48,
			Unit:      "",
			Type:      FloatVariableType,
			Precision: 3,
			Sort:      20,
		},
	}
}
